language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script: "pytest && pylint karmanor.py --errors-only"
notifications:
  email: false
  webhooks:
    urls:
      - https://mechilles.herokuapp.com/webhook_karmanor
    on_success: change