language: node_js
node_js:
  - "10"
cache: npm

os:
  - windows
  - linux
  - osx

before_script:
- npm ci
- npm i codecov -g
- npm run dev

script:
- npm run lint
- npm test

notifications:
  email: false
  webhooks:
    urls:
      - https://mechilles.garkaklis.com/
    on_success: never

after_success:
  - codecov -s tests/coverage
