language: node_js
node_js:
  - "10"
  - "9"
  - "8"
cache: npm

os:
  - linux
  - osx

before_script:
- npm ci

script:
- npm run development:test
- npm test

notifications:
  email: false

after_success:
  - codecov
