language: node_js
node:
  - 10
  - 8
cache: npm

os:
  - linux
  - osx

before_script:
- npm ci

script:
- npm run development:test
- npm test

notifications:
  email: false

after_success:
  - codecov
