language: node_js
node_js:
  - "10"
cache: npm

os:
  - linux
  - osx

before_script:
- npm ci
- npm i codecov -g
- npm run dev

script:
- npm run lint
- npm test

notifications:
  email: false

after_success:
  - codecov
