jobs:
  - job: Test
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - bash: npm ci
        displayName: 'Install dependencies'

      - bash: npm i codecov -g
        displayName: 'Install codecov globally'

      - bash: npm run development
        displayName: 'Compile Karmanor'

      - bash: npm run lint
        displayName: 'Lint code'

      - bash: npm run test
        displayName: 'Test Karmanor'

      - bash: codecov -t $(codecovToken)
        displayName: 'Upload to codecov'

  # - job: Build
  #   pool:
  #     vmImage: 'vs2017-win2016'
  #   steps:
  #     - bash: |
  #         npm ci
  #       displayName: 'Install dependencies'

  #     - bash: npm run production
  #       displayName: 'Compile Karmanor'

  #     - bash: 'npm run pack:all'
  #       displayName: 'Pack Karmanor for all platforms'

  #     - powershell: |
  #         Compress-Archive -Path $(Build.Repository.LocalPath)/dist/* -CompressionLevel Optimal -DestinationPath $(Build.Repository.LocalPath)/Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip
  #       displayName: 'Zip Karmanor builds'

  #     - task: PublishBuildArtifacts@1
  #       inputs:
  #         pathtoPublish: '$(Build.Repository.LocalPath)/Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip'
  #         artifactName: 'Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip'
