jobs:
  - job: Test
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - bash: npm ci
        displayName: 'Install dependencies'

      - bash: npm run development
        displayName: 'Compile Karmanor'

      - bash: npm run lint
        displayName: 'Lint code'

      - bash: npm run test
        displayName: 'Test Karmanor'

  - job: Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - bash: |
          sudo apt-get install zip
          npm ci
        displayName: 'Install dependencies'

      - bash: npm run production
        displayName: 'Compile Karmanor'

      - bash: 'npm run pack:all'
        displayName: 'Pack Karmanor for all platforms'

      - bash: |
          'zip -r9 $(Build.ArtifactStagingDirectory)/Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip $(Build.Repository.LocalPath)/dist/'
        displayName: 'Zip Karmanor builds'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip'
          artifactName: 'Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip'
