jobs:
  - job: Test
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'

      - script: npm ci & npm i codecov -g
        displayName: 'Install dependencies'

      - task: Bash@3
        inputs:
          script: 'npm run dev'

      - script: npm run lint
        displayName: 'Lint code'

      - script: npm run test
        displayName: 'Test Karmanor'

      - script: codecov
        displayName: 'Upload coverage'
        condition: succeeded()

  - job: Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'

      - script: npm ci
        displayName: 'Install dependencies'

      - task: Bash@3
        inputs:
          script: 'npm run pack:all'

      - script: move dist/ $(Build.BinariesDirectory)
        displayName: 'Move dist directory to binary directory'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)/dist'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)/Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip
          artifactName: Karmanor_$(Build.BuildId).zip
