jobs:
  - job: Test
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'

      - bash: npm ci
        displayName: 'Install dependencies'

      - bash: npm run dev
        displayName: 'Compile Karmanor'

      - bash: npm run lint
        displayName: 'Lint code'

      - bash: npm run test
        displayName: 'Test Karmanor'

  - job: Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'

      - script: npm ci
        displayName: 'Install dependencies'

      - script: 'npm run pack:all'
        displayName: 'Pack Karmanor for all platforms'

      - script: mv 'dist/' '$(Build.BinariesDirectory)'
        displayName: 'Move dist directory to binary directory'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)/dist'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)/Karmanor_$(Build.SourceBranchName)_$(Build.BuildId).zip
          artifactName: Karmanor_$(Build.BuildId).zip
